/*
 * Telstra Messaging API
 *
 * The Telstra Messaging API specification
 *
 * The version of the OpenAPI document: 2.2.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Telstra.Messaging.Client.OpenAPIDateConverter;

namespace Telstra.Messaging.Model
{
    /// <summary>
    /// MessageSentResponse
    /// </summary>
    [DataContract(Name = "MessageSentResponse")]
    public partial class MessageSentResponse : IEquatable<MessageSentResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MessageSentResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MessageSentResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MessageSentResponse" /> class.
        /// </summary>
        /// <param name="messages">An array of messages. (required).</param>
        /// <param name="country">An array of the countries to which the destination MSISDNs belong..</param>
        /// <param name="messageType">This returns whether the message sent was a SMS or MMS. (required).</param>
        /// <param name="numberSegments">For SMS messages only, the value indicates the number of 160 character message segments sent.  (required).</param>
        public MessageSentResponse(List<Message> messages = default(List<Message>), List<Object> country = default(List<Object>), string messageType = default(string), int numberSegments = default(int))
        {
            // to ensure "messages" is required (not null)
            if (messages == null)
            {
                throw new ArgumentNullException("messages is a required property for MessageSentResponse and cannot be null");
            }
            this.Messages = messages;
            // to ensure "messageType" is required (not null)
            if (messageType == null)
            {
                throw new ArgumentNullException("messageType is a required property for MessageSentResponse and cannot be null");
            }
            this.MessageType = messageType;
            this.NumberSegments = numberSegments;
            this.Country = country;
        }

        /// <summary>
        /// An array of messages.
        /// </summary>
        /// <value>An array of messages.</value>
        [DataMember(Name = "messages", IsRequired = true, EmitDefaultValue = true)]
        public List<Message> Messages { get; set; }

        /// <summary>
        /// An array of the countries to which the destination MSISDNs belong.
        /// </summary>
        /// <value>An array of the countries to which the destination MSISDNs belong.</value>
        [DataMember(Name = "Country", EmitDefaultValue = false)]
        public List<Object> Country { get; set; }

        /// <summary>
        /// This returns whether the message sent was a SMS or MMS.
        /// </summary>
        /// <value>This returns whether the message sent was a SMS or MMS.</value>
        /// <example>&quot;SMS&quot;</example>
        [DataMember(Name = "messageType", IsRequired = true, EmitDefaultValue = true)]
        public string MessageType { get; set; }

        /// <summary>
        /// For SMS messages only, the value indicates the number of 160 character message segments sent. 
        /// </summary>
        /// <value>For SMS messages only, the value indicates the number of 160 character message segments sent. </value>
        /// <example>1</example>
        [DataMember(Name = "numberSegments", IsRequired = true, EmitDefaultValue = true)]
        public int NumberSegments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MessageSentResponse {\n");
            sb.Append("  Messages: ").Append(Messages).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  MessageType: ").Append(MessageType).Append("\n");
            sb.Append("  NumberSegments: ").Append(NumberSegments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MessageSentResponse);
        }

        /// <summary>
        /// Returns true if MessageSentResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of MessageSentResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessageSentResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Messages == input.Messages ||
                    this.Messages != null &&
                    input.Messages != null &&
                    this.Messages.SequenceEqual(input.Messages)
                ) && 
                (
                    this.Country == input.Country ||
                    this.Country != null &&
                    input.Country != null &&
                    this.Country.SequenceEqual(input.Country)
                ) && 
                (
                    this.MessageType == input.MessageType ||
                    (this.MessageType != null &&
                    this.MessageType.Equals(input.MessageType))
                ) && 
                (
                    this.NumberSegments == input.NumberSegments ||
                    this.NumberSegments.Equals(input.NumberSegments)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Messages != null)
                {
                    hashCode = (hashCode * 59) + this.Messages.GetHashCode();
                }
                if (this.Country != null)
                {
                    hashCode = (hashCode * 59) + this.Country.GetHashCode();
                }
                if (this.MessageType != null)
                {
                    hashCode = (hashCode * 59) + this.MessageType.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.NumberSegments.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
