/*
 * Telstra Messaging API
 *
 * The Telstra Messaging API specification
 *
 * The version of the OpenAPI document: 2.2.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telstra.Messaging.Model;
using Telstra.Messaging.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telstra.Messaging.Test.Model
{
    /// <summary>
    ///  Class for testing MessageSentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MessageSentResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MessageSentResponse
        //private MessageSentResponse instance;

        public MessageSentResponseTests()
        {
            // TODO uncomment below to create an instance of MessageSentResponse
            //instance = new MessageSentResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessageSentResponse
        /// </summary>
        [Fact]
        public void MessageSentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" MessageSentResponse
            //Assert.IsType<MessageSentResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'MessageType'
        /// </summary>
        [Fact]
        public void MessageTypeTest()
        {
            // TODO unit test for the property 'MessageType'
        }
        /// <summary>
        /// Test the property 'NumberSegments'
        /// </summary>
        [Fact]
        public void NumberSegmentsTest()
        {
            // TODO unit test for the property 'NumberSegments'
        }

    }

}
